### ISSUE TITLE
Support .Net 3.5?

### ISSUE THREAD

**Issue by mofirouz** [seanmcelroy/QuicDotNet#1]
Hi there,

Thanks for the great work. A couple of questions:

- Does your library support Unity3D?
- Does your library support .Net 3.5? (or even lower if possible, because of Unity again?)

Cheers,
Mo.

**Comment by seanmcelroy** [comment]
Hi there - the library is not portable and I have not validated it is usable by either Unity or .NET 3.5, mostly because the implementation is not yet complete.

**Comment by mofirouz** [comment]
Hi Sean - Thanks for the reply. 

By the way, your blog posts are amazing! Especially the ones about Alkami and your experiences so far. 

Cheers,
Mo.
